# -*- coding: utf-8 -*-
"""math project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iCIH7AgedPHMhrKJgEjnXkicT0l3GmEx
"""

import numpy as np
import pandas as pd
#creating dictionairies
movies_data = [
    # Allu Arjun
    {"title": "Arya", "genre": "Romance", "hero": "Allu Arjun"},
    {"title": "Arya 2", "genre": "Romance", "hero": "Allu Arjun"},
    {"title": "Bunny", "genre": "Action", "hero": "Allu Arjun"},
    {"title": "Julayi", "genre": "Action", "hero": "Allu Arjun"},
    {"title": "Race Gurram", "genre": "Action", "hero": "Allu Arjun"},
    {"title": "Sarrainodu", "genre": "Action", "hero": "Allu Arjun"},
    {"title": "Ala Vaikunthapurramuloo", "genre": "Family", "hero": "Allu Arjun"},
    {"title": "Pushpa", "genre": "Action", "hero": "Allu Arjun"},
    {"title": "Pushpa 2", "genre": "Action", "hero": "Allu Arjun"},

    # Mahesh Babu
    {"title": "Okkadu", "genre": "Action", "hero": "Mahesh Babu"},
    {"title": "Athadu", "genre": "Action", "hero": "Mahesh Babu"},
    {"title": "Pokiri", "genre": "Action", "hero": "Mahesh Babu"},
    {"title": "Dookudu", "genre": "Action", "hero": "Mahesh Babu"},
    {"title": "Srimanthudu", "genre": "Family", "hero": "Mahesh Babu"},
    {"title": "Bharat Ane Nenu", "genre": "Drama", "hero": "Mahesh Babu"},
    {"title": "Maharshi", "genre": "Drama", "hero": "Mahesh Babu"},
    {"title": "Sarileru Neekevvaru", "genre": "Action", "hero": "Mahesh Babu"},

    # Prabhas
    {"title": "Varsham", "genre": "Romance", "hero": "Prabhas"},
    {"title": "Chatrapathi", "genre": "Action", "hero": "Prabhas"},
    {"title": "Darling", "genre": "Romance", "hero": "Prabhas"},
    {"title": "Mr Perfect", "genre": "Romance", "hero": "Prabhas"},
    {"title": "Mirchi", "genre": "Action", "hero": "Prabhas"},
    {"title": "Baahubali: The Beginning", "genre": "Action", "hero": "Prabhas"},
    {"title": "SALAAR", "genre": "Action", "hero": "Prabhas"},
    {"title": "Baahubali 2: The Conclusion", "genre": "Action", "hero": "Prabhas"},

    # Jr NTR
    {"title": "Student No.1", "genre": "Drama", "hero": "Jr NTR"},
    {"title": "Simhadri", "genre": "Action", "hero": "Jr NTR"},
    {"title": "Yamadonga", "genre": "Fantasy", "hero": "Jr NTR"},
    {"title": "Brindavanam", "genre": "Family", "hero": "Jr NTR"},
    {"title": "Temper", "genre": "Action", "hero": "Jr NTR"},
    {"title": "Nannaku Prematho", "genre": "Thriller", "hero": "Jr NTR"},
    {"title": "Janatha Garage", "genre": "Action", "hero": "Jr NTR"},
    {"title": "Aravinda Sametha", "genre": "Action", "hero": "Jr NTR"},

    # Ram Charan
    {"title": "Chirutha", "genre": "Action", "hero": "Ram Charan"},
    {"title": "Magadheera", "genre": "Action", "hero": "Ram Charan"},
    {"title": "Orange", "genre": "Romance", "hero": "Ram Charan"},
    {"title": "Racha", "genre": "Action", "hero": "Ram Charan"},
    {"title": "Yevadu", "genre": "Action", "hero": "Ram Charan"},
    {"title": "Dhruva", "genre": "Thriller", "hero": "Ram Charan"},
    {"title": "Rangasthalam", "genre": "Drama", "hero": "Ram Charan"},

    # Vijay Deverakonda
    {"title": "Pelli Choopulu", "genre": "Romance", "hero": "Vijay Deverakonda"},
    {"title": "Arjun Reddy", "genre": "Romance", "hero": "Vijay Deverakonda"},
    {"title": "Geetha Govindam", "genre": "Romance", "hero": "Vijay Deverakonda"},
    {"title": "Taxiwaala", "genre": "Thriller", "hero": "Vijay Deverakonda"},
    {"title": "Dear Comrade", "genre": "Drama", "hero": "Vijay Deverakonda"},
    {"title": "World Famous Lover", "genre": "Romance", "hero": "Vijay Deverakonda"},
    {"title": "Kushi", "genre": "Romance", "hero": "Vijay Deverakonda"},

    # Nani
    {"title": "Ashta Chamma", "genre": "Comedy", "hero": "Nani"},
    {"title": "Ala Modalaindi", "genre": "Romance", "hero": "Nani"},
    {"title": "Eega", "genre": "Fantasy", "hero": "Nani"},
    {"title": "Nenu Local", "genre": "Comedy", "hero": "Nani"},
    {"title": "Ninnu Kori", "genre": "Romance", "hero": "Nani"},
    {"title": "MCA", "genre": "Family", "hero": "Nani"},
    {"title": "Jersey", "genre": "Drama", "hero": "Nani"},
    {"title": "Hi Nanna", "genre": "Romance", "hero": "Nani"},

    # Pawan Kalyan
    {"title": "Tholi Prema", "genre": "Romance", "hero": "Pawan Kalyan"},
    {"title": "Kushi", "genre": "Romance", "hero": "Pawan Kalyan"},
    {"title": "Jalsa", "genre": "Comedy", "hero": "Pawan Kalyan"},
    {"title": "Gabbar Singh", "genre": "Action", "hero": "Pawan Kalyan"},
    {"title": "Attarintiki Daredi", "genre": "Family", "hero": "Pawan Kalyan"},
    {"title": "Agnyaathavaasi", "genre": "Drama", "hero": "Pawan Kalyan"},

    # Chiranjeevi
    {"title": "Indra", "genre": "Action", "hero": "Chiranjeevi"},
    {"title": "Tagore", "genre": "Drama", "hero": "Chiranjeevi"},
    {"title": "Shankar Dada MBBS", "genre": "Comedy", "hero": "Chiranjeevi"},
    {"title": "Stalin", "genre": "Drama", "hero": "Chiranjeevi"},
    {"title": "Khaidi No 150", "genre": "Action", "hero": "Chiranjeevi"},
    {"title": "Sye Raa Narasimha Reddy", "genre": "Action", "hero": "Chiranjeevi"},

    # Ravi Teja
    {"title": "Idiot", "genre": "Action", "hero": "Ravi Teja"},
    {"title": "Amma Nanna O Tamila Ammayi", "genre": "Drama", "hero": "Ravi Teja"},
    {"title": "Vikramarkudu", "genre": "Action", "hero": "Ravi Teja"},
    {"title": "Kick", "genre": "Comedy", "hero": "Ravi Teja"},
    {"title": "Balupu", "genre": "Action", "hero": "Ravi Teja"},
    {"title": "Raja The Great", "genre": "Action", "hero": "Ravi Teja"},

    # Nagarjuna
    {"title": "Shiva", "genre": "Action", "hero": "Nagarjuna"},
    {"title": "Ninne Pelladatha", "genre": "Romance", "hero": "Nagarjuna"},
    {"title": "Manmadhudu", "genre": "Romance", "hero": "Nagarjuna"},
    {"title": "Manam", "genre": "Family", "hero": "Nagarjuna"},
    {"title": "Soggade Chinni Nayana", "genre": "Family", "hero": "Nagarjuna"},
    {"title": "Gaganam", "genre": "Thriller", "hero": "Nagarjuna"},
]
#arrange genres and heros in alphabetical order
all_genres = sorted(set(m["genre"] for m in movies_data))
all_heroes = sorted(set(m["hero"] for m in movies_data))

print("Available Genres in this Telugu dataset:")
for g in all_genres:
    print(" -", g)

print("\nAvailable Heroes:")
for h in all_heroes:
    print(" -", h)

print("\nHero vs Genre :")
for hero in all_heroes:
    hero_genres = sorted(set(m["genre"] for m in movies_data if m["hero"] == hero))
    print(f"\nHero: {hero}")
    print(f"  Has genres: {', '.join(hero_genres)}")

while True:
    try:
        num_users = int(input("\nEnter number of users: "))
        if num_users <= 0:
            raise ValueError
        break
    except ValueError:
        print("Please enter a valid positive integer for number of users.")

user_names = []
print("\nEnter each user's name :")
for i in range(num_users):
    name = input(f"  Name of User {i+1}: ").strip()
    if name == "":
        name = f"User{i+1}"
    user_names.append(name)

#checks if a movie matches the user's filters
def match_filter(movie, genre_f, hero_f):
    genre_ok = (genre_f.lower() == "all") or (movie["genre"].lower() == genre_f.lower())
    hero_ok  = (hero_f.lower() == "all") or (movie["hero"] == hero_f)
    return genre_ok and hero_ok

while True:
    genre_filter = input("\nEnter preferred genre (or 'all' for no filter): ").strip()
    hero_filter = input("Enter preferred hero (or 'all' for no filter): ").strip()

    if genre_filter.lower() != "all" and genre_filter not in all_genres:
        print("\nInvalid genre! Please choose from the available genre list shown above.")
        continue
    if hero_filter.lower() == "all":
        break
    # check hero valid
    if hero_filter not in all_heroes:
        print("\nInvalid hero name! Please choose from the available hero list shown above.")
        continue

    # check hero has that genre
    hero_genres = sorted(set(m["genre"] for m in movies_data if m["hero"] == hero_filter))

    if genre_filter.lower() != "all" and genre_filter not in hero_genres:
        print(f"\n {hero_filter} has NO movies in '{genre_filter}' genre in this dataset.")
        print("Please select a different genre.")
        continue

    # if exactly ONE movie of that hero in that genre
    if genre_filter.lower() != "all":
        movies_in_genre_for_hero = [
            m for m in movies_data
            if m["hero"] == hero_filter and m["genre"] == genre_filter
        ]
        if len(movies_in_genre_for_hero) == 1:
            print(f"\n {hero_filter} has ONLY ONE movie in '{genre_filter}' genre in this dataset:")
            print(f"   -> {movies_in_genre_for_hero[0]['title']}")
            again = input("Do you want to choose genre again? or watch this only one movie in this genre done by the hero (y/n): ").strip().lower()
            if again == 'y':
                continue
    break

# display movies matching with hero and genre
selected_indices = [
    idx for idx, m in enumerate(movies_data)
    if match_filter(m, genre_filter, hero_filter)
]
selected_movies = [movies_data[i] for i in selected_indices]

if not selected_movies:
    print("\nNo movies match your filters. Try running again with 'all' or a different choice.")
    raise SystemExit

movie_names = [m["title"] for m in selected_movies]
num_movies = len(movie_names)

print("\nFinal Selected Telugu Movies for Rating :")
for i, title in enumerate(movie_names, start=1):
    hero = selected_movies[i-1]["hero"]
    genre = selected_movies[i-1]["genre"]
    print(f"  {i}. {title}  ({genre} | {hero})")

print("\nEnter ratings for each user.")
print("If a user has NOT watched a movie, enter 0.")
print("Ratings can be integers or decimals (e.g., 3, 4.5).")

ratings_list = []
for u, uname in enumerate(user_names):
    print(f"\nEnter ratings for {uname}:")
    row = []
    for m, mtitle in enumerate(movie_names):
        while True:
            val = input(f"  Rating for '{mtitle}' (0 if not watched): ").strip()
            try:
                rating = float(val)
                row.append(rating)
                break
            except ValueError:
                print("    Invalid input — please enter a number (e.g., 0, 3, 4.5).")
    ratings_list.append(row)
#Converts the numpy matrix into a table for displaying only(pandas)
ratings = np.array(ratings, dtype=float) if False else np.array(ratings_list, dtype=float)
ratings_df = pd.DataFrame(ratings, index=user_names, columns=movie_names)
print("\nOriginal Rating Sub-Matrix (rows = users, columns = selected movies):")
print(ratings_df)
#svd starts
rows, cols = ratings.shape
if rows == 0 or cols == 0:
    print("\nNot enough data to perform SVD.")
    raise SystemExit

U, S, VT = np.linalg.svd(ratings, full_matrices=False)
S_diag = np.diag(S)

#Low-Rank Approximation and remove unusefull data
# reduces svd and creatingn rating matrix
rank_approx = min(2, len(S), rows, cols)
if rank_approx == 0:
    print("\nNot enough information for SVD-based prediction.")
    predicted_ratings = ratings.copy()
else:
    U_k = U[:, :rank_approx]
    S_k = S_diag[:rank_approx, :rank_approx]
    VT_k = VT[:rank_approx, :]
    predicted_ratings = U_k.dot(S_k).dot(VT_k)

pred_df = pd.DataFrame(
    np.round(predicted_ratings, 2),
    index=user_names,
    columns=movie_names
)

print("\nPredicted Rating Matrix (after SVD approximation):")
print(pred_df)
#recommending
def recommend_movies(user_index, original, predicted, top_n=3):
    user_ratings = original[user_index]
    user_predictions = predicted[user_index]

    # prefer unrated movies (original == 0)
    candidates = [
        (movie_names[i], user_predictions[i])
        for i in range(len(user_ratings))
        if user_ratings[i] == 0
    ]

    # if all are rated, fallback to all
    if not candidates:
        candidates = [
            (movie_names[i], user_predictions[i])
            for i in range(len(user_ratings))
        ]

    candidates.sort(key=lambda x: x[1], reverse=True)
    return candidates[:top_n]

for u_idx, uname in enumerate(user_names):
    ans = input(f"\nDo you want recommendations for {uname}? (y/n): ").strip().lower()
    if ans != 'y':
        continue

    recs = recommend_movies(u_idx, ratings, predicted_ratings, top_n=3)
    print(f"\nTop 3 recommendations for {uname} based on SVD:")
    for movie, score in recs:
        print(f"  {movie}  (predicted rating: {score:.2f})")

print("\nThank you for using this movie recommendation system! ")